### PR TITLE
Add a motd

### PR DESCRIPTION
**Pull request by l3gacyb3ta**

### CODE REVIEW

**Comment by CodeLongAndProsper90** [comment]
Can you write this using `builtins.readFile`?
I think that something like this is cleaner:
```nix
{ ... }:
{
  users.motd = builtins.readFile ./motd.txt;
}
```
Additionally, `users/default.nix` is an automatically generated file (I know this needs to be documented)- I think something like `motd.nix` would be better, because the `users/` tree is supposed to only be for accounts / permissions.

**Comment by l3gacyb3ta** [comment]
ahhhhh perfect. I'll rework that

**Comment by CodeLongAndProsper90** [comment]
I also think it could be better to have the MOTD reference a wiki article about irc that include instructions- that way we don't need to rebuild it.
(Also some ASCII art in it would be great, think `figlet`)

**Comment by l3gacyb3ta** [comment]
Ahhhh that'd be smart, but is the wiki working right now?

**Comment by l3gacyb3ta** [comment]
Also I'll try and make a HackClub logo ASCII Art!

**Comment by CodeLongAndProsper90** [comment]
For the logo you could look at [tilde.hackclub.com](https://tilde.hackclub.com), and no, but that's cause HQ got flooded and port `1965` isn't forwarded again

**Comment by CodeLongAndProsper90** [comment]
Hmm, I think using a different font for the welcome could look better, something like `figlet`'s `big` or `slant`

**Comment by CodeLongAndProsper90** [comment]
I'd also include the command to get to the wiki, probably `gemini://tilde.hackclub.com/wiki/Tutorials/irc`

**Comment by l3gacyb3ta** [comment]
tada

**Comment by CodeLongAndProsper90** [comment]
You also need to import `motd.nix` in `configuration.nix`

**Comment by l3gacyb3ta** [comment]
.-. duh

**Comment by l3gacyb3ta** [comment]
yay

**Pull request merged**
